# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 21:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
        ('eventos', '0003_remove_asistencia_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='inasistencia',
            name='evento',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='eventos.Evento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='inasistencia',
            name='socio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='asociacion.SocioLote'),
            preserve_default=False,
        ),
    ]
