# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0004_auto_20161103_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote'),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='socio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote'),
        ),
    ]
