# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 22:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0005_auto_20161103_1656'),
    ]

    operations = [
        migrations.RenameField(
            model_name='asistencia',
            old_name='socio',
            new_name='lote',
        ),
    ]
