# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 23:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0006_auto_20161103_1700'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='modificacion',
            field=models.DateField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74373)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modificacion',
            field=models.DateField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74373)),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='creacion',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74322, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='modificacion',
            field=models.DateField(default=datetime.datetime(2016, 11, 3, 23, 9, 40, 74373)),
        ),
    ]
