# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0007_auto_20161103_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='asistencia',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='asistencia',
            name='modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='modificacion',
            field=models.DateField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inasistencia',
            name='modificacion',
            field=models.DateField(auto_now=True),
        ),
    ]
