# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-15 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0009_auto_20161109_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='asistencia',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
