# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auths', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InformacionLote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('area_lote', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='area total')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'InformacionLotes',
                'verbose_name': 'InformacionLote',
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('item', models.IntegerField(default=1)),
                ('lote', models.CharField(max_length=3, unique=True, verbose_name='ingrese lote')),
                ('estado', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Lotes',
                'verbose_name': 'Lote',
            },
        ),
        migrations.CreateModel(
            name='Manzana',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('manzana', models.CharField(max_length=3, unique=True, verbose_name='ingrese manzana')),
            ],
            options={
                'verbose_name_plural': 'Manzanas',
                'verbose_name': 'Manzana',
            },
        ),
        migrations.CreateModel(
            name='Socio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado_civil', models.CharField(choices=[('Soltero', 'Soltero'), ('Casado', 'Casado'), ('Viudo', 'Viudo'), ('Divorsiado', 'Divorsiado')], max_length=20)),
                ('domicilio', models.CharField(blank=True, max_length=300, null=True)),
                ('procedencia', models.CharField(blank=True, max_length=50, null=True)),
                ('celular', models.CharField(blank=True, max_length=30, null=True)),
                ('telefono', models.CharField(blank=True, max_length=30, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('residencia_juliaca', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('is_adventista', models.CharField(choices=[('Si', 'Si'), ('No', 'No')], max_length=2)),
                ('estado', models.BooleanField(default=True)),
                ('conyuge', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='asociacion.Socio')),
                ('persona', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auths.Person')),
            ],
            options={
                'verbose_name_plural': 'Socios',
                'verbose_name': 'Socio',
            },
        ),
        migrations.CreateModel(
            name='SocioLote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lote_socio', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Socio')),
            ],
            options={
                'verbose_name_plural': 'SocioLotes',
                'verbose_name': 'SocioLote',
            },
        ),
        migrations.AddField(
            model_name='lote',
            name='manzana',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Manzana'),
        ),
        migrations.AddField(
            model_name='informacionlote',
            name='informacion_lote',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='asociacion.Lote'),
        ),
    ]
