# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 21:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('asociacion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='socio',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='asociacion.Socio'),
            preserve_default=False,
        ),
    ]
