# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-03 23:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pago',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='periodo',
            name='fecha',
        ),
        migrations.AlterField(
            model_name='pago',
            name='inasistencia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.Inasistencia'),
        ),
        migrations.AlterField(
            model_name='periodo',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
