# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-11-09 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pagos', '0005_auto_20161103_2310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='periodo',
            name='nombre',
            field=models.CharField(default='', max_length=50),
        ),
    ]
